---
language: python

python: "2.7"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install openjdk-7-jre -qq

install:
  # Install Ansible.
  - pip install ansible

script:
        # playbook syntax
        - "ansible-playbook -i tests/inventory tests/travis.yml --syntax-check"
        # execute role
        - "ansible-playbook -i tests/inventory tests/travis.yml --connection=local --sudo --tags 'jenkins_master_install,jenkins_master_config'"
        # check port of jenkins
        - "curl http://localhost:8080"
